INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('1', 'Agincourt North');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('2', 'Agincourt South-Malvern West');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('3', 'Alderwood');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('4', 'Annex');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('5', 'Banbury-Don Mills');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('6', 'Bathurst Manor');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('7', 'Bay Street Corridor');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('8', 'Bayview Village');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('9', 'Bayview Woods-Steeles');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('10', 'Bedford Park-Nortown');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('11', 'Beechborough-Greenbrook');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('12', 'Bendale');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('13', 'Birchcliffe-Cliffside');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('14', 'Black Creek');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('15', 'Blake-Jones');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('16', 'Briar Hill-Belgravia');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('17', 'Bridle Path-Sunnybrook-York Mills');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('18', 'Broadview North');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('19', 'Brookhaven-Amesbury');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('20', 'Cabbagetown-South St.James Town');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('21', 'Caledonia-Fairbank');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('22', 'Casa Loma');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('23', 'Centennial Scarborough');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('24', 'Church-Yonge Corridor');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('25', 'Clairlea-Birchmount');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('26', 'Clanton Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('27', 'Cliffcrest');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('28', 'Corso Italia-Davenport');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('29', 'Danforth');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('30', 'Danforth East York');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('31', 'Don Valley Village');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('32', 'Dorset Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('33', 'Dovercourt-Wallace Emerson-Junction');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('34', 'Downsview-Roding-CFB');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('35', 'Dufferin Grove');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('36', 'East End-Danforth');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('37', 'Edenbridge-Humber Valley');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('38', 'Eglinton East');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('39', 'Elms-Old Rexdale');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('40', 'Englemount-Lawrence');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('41', 'Eringate-Centennial-West Deane');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('42', 'Etobicoke West Mall');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('43', 'Flemingdon Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('44', 'Forest Hill North');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('45', 'Forest Hill South');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('46', 'Glenfield-Jane Heights');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('47', 'Greenwood-Coxwell');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('48', 'Guildwood');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('49', 'Henry Farm');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('50', 'Highland Creek');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('51', 'High Park North');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('52', 'High Park-Swansea');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('53', 'Hillcrest Village');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('54', 'Humber Heights-Westmount');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('55', 'Humbermede');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('56', 'Humber Summit');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('57', 'Humewood-Cedarvale');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('58', 'Ionview');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('59', 'Islington-City Centre West');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('60', 'Junction Area');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('61', 'Keelesdale-Eglinton West');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('62', 'Kennedy Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('63', 'Kensington-Chinatown');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('64', 'Kingsview Village-The Westway');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('65', 'Kingsway South');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('66', 'Lambton Baby Point');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('67', 'L''Amoreaux');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('68', 'Lansing-Westgate');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('69', 'Lawrence Park North');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('70', 'Lawrence Park South');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('71', 'Leaside-Bennington');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('72', 'Little Portugal');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('73', 'Long Branch');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('74', 'Malvern');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('75', 'Maple Leaf');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('76', 'Markland Wood');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('77', 'Milliken');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('78', 'Mimico (includes Humber Bay Shores)');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('79', 'Morningside');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('80', 'Moss Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('81', 'Mount Dennis');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('82', 'Mount Olive-Silverstone-Jamestown');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('83', 'Mount Pleasant East');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('84', 'Mount Pleasant West');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('85', 'Newtonbrook East');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('86', 'Newtonbrook West');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('87', 'New Toronto');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('88', 'Niagara');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('89', 'North Riverdale');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('90', 'North St.James Town');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('91', 'Oakridge');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('92', 'Oakwood Village');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('93', 'O''Connor-Parkview');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('94', 'Old East York');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('95', 'Palmerston-Little Italy');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('96', 'Parkwoods-Donalda');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('97', 'Pelmo Park-Humberlea');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('98', 'Playter Estates-Danforth');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('99', 'Pleasant View');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('100', 'Princess-Rosethorn');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('101', 'Regent Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('102', 'Rexdale-Kipling');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('103', 'Rockcliffe-Smythe');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('104', 'Roncesvalles');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('105', 'Rosedale-Moore Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('106', 'Rouge');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('107', 'Runnymede-Bloor West Village');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('108', 'Rustic');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('109', 'Scarborough Village');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('110', 'South Parkdale');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('111', 'South Riverdale');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('112', 'St.Andrew-Windfields');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('113', 'Steeles');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('114', 'Stonegate-Queensway');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('115', 'Tam O''Shanter-Sullivan');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('116', 'Taylor-Massey');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('117', 'The Beaches');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('118', 'Thistletown-Beaumond Heights');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('119', 'Thorncliffe Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('120', 'Trinity-Bellwoods');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('121', 'University');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('122', 'Victoria Village');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('123', 'Waterfront Communities-The Island');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('124', 'West Hill');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('125', 'West Humber-Clairville');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('126', 'Westminster-Branson');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('127', 'Weston');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('128', 'Weston-Pellam Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('129', 'Wexford/Maryvale');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('130', 'Willowdale East');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('131', 'Willowdale West');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('132', 'Willowridge-Martingrove-Richview');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('133', 'Woburn');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('134', 'Woodbine Corridor');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('135', 'Woodbine-Lumsden');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('136', 'Wychwood');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('137', 'Yonge-Eglinton');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('138', 'Yonge-St.Clair');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('139', 'Yorkdale-Glen Park');
INSERT INTO neighbourhoods (neighbourhood_id, neighbourhood_name) VALUES ('140', 'York University Heights');
