INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('1', 'D11', '103');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('2', 'D12', '93');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('3', 'D13', '15');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('4', 'D14', '107');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('5', 'D22', '72');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('6', 'D23', '21');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('7', 'D31', '103');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('8', 'D32', '122');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('9', 'D33', '75');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('10', 'D41', '88');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('11', 'D42', '117');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('12', 'D43', '100');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('13', 'D51', '104');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('14', 'D52', '131');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('15', 'D53', '53');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('16', 'D55', '2');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('17', 'D55', '88');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('18', 'Traffic Services', '38');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('19', 'East Collision Reporting Centre', '130');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('20', 'North Collision Reporting Centre', '21');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('21', 'Mounted Unit', '58');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('22', 'Toronto Police College', '22');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('23', 'Headquarters', '89');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('24', 'Parking Enforcement East/Property & Evidence Management', '49');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('25', 'Parking Enforcement West', '59');
INSERT INTO police_stations (police_station_id, police_station_name, neighbourhood_id) VALUES ('26', 'Marine Headquarters', '15');
