INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('1', '299 Queen Street West', '103');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('2', 'Aga Khan Museum', '93');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('3', 'Al Green Theatre (at the Miles Nadal Jewish Community Centre)', '15');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('4', 'Alexander Muir Memorial Gardens', '107');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('5', 'Allan Gardens', '72');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('6', 'Alumnae Theatre', '21');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('7', 'Arcadia Earth', '103');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('8', 'Art Gallery of Ontario', '122');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('9', 'Art Museum at the University of Toronto', '75');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('10', 'Artscape Wychwood Barns', '88');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('11', 'Ashbridges Bay Park', '117');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('12', 'Balmy Beach Park', '100');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('13', 'BAPS Shri Swaminarayan Mandir', '104');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('14', 'Bata Shoe Museum', '131');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('15', 'Beanfield Centre', '53');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('16', 'Betty Oliphant Theatre (at Canada''s National Ballet School)', '2');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('17', 'Billy Bishop Toronto City Airport', '88');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('18', 'Bluffer''s Park and Beach (Scarborough Bluffs)', '38');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('19', 'BMO Field', '130');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('20', 'Bubble Planet', '21');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('21', 'Buddies in Bad Times Theatre', '58');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('22', 'Budweiser Stage', '22');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('23', 'CAA Ed Mirvish Theatre', '89');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('24', 'CAA Theatre (formerly Panasonic Theatre)', '49');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('25', 'Campbell House', '59');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('26', 'Canada''s Walk of Fame', '15');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('27', 'Canadian Museum of Cultural Heritage of Indo-Canadian', '51');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('28', 'Canadian Sculpture Centre', '108');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('29', 'Canadian Stage (Berkeley Street Theatre)', '55');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('30', 'Casa Loma', '64');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('31', 'Cedar Ridge Creative Centre', '131');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('32', 'Centennial Park', '51');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('33', 'Centennial Park Conservatory', '135');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('34', 'Centre Island Beach', '21');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('35', 'Centreville Amusement Park', '73');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('36', 'CF Fairview Mall', '18');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('37', 'CF Sherway Gardens', '132');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('38', 'CF Toronto Eaton Centre', '89');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('39', 'Cherry Beach/ Clarke Beach Park', '60');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('40', 'Chinese Cultural Centre of Greater Toronto', '14');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('41', 'CN Tower', '9');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('42', 'Coca-Cola Coliseum (formerly Ricoh Coliseum)', '90');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('43', 'Colborne Lodge', '53');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('44', 'Dancemakers Centre for Creation', '130');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('45', 'Design Exchange', '84');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('46', 'Downsview Park', '92');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('47', 'Elgin and Winter Garden Theatre Centre', '111');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('48', 'Enercare Centre', '8');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('49', 'Evergreen Brick Works', '35');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('50', 'Exhibition Place', '81');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('51', 'Factory Theatre', '50');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('52', 'Famous People Players', '104');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('53', 'Fort York National Historic Site', '132');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('54', 'Four Seasons Centre for the Performing Arts', '2');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('55', 'Franklin Children''s Garden', '134');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('56', 'Gardiner Museum', '54');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('57', 'George Ignatieff Theatre', '106');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('58', 'Gibraltar Point Beach', '4');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('59', 'Gibson House Museum', '54');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('60', 'Glenn Gould Studio', '44');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('61', 'Gooderham Flatiron Building', '14');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('62', 'Graffiti Alley', '95');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('63', 'Guild Park and Gardens (formely known as Guildwood Park)', '48');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('64', 'Hanlan''s Point Beach', '15');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('65', 'Harbour Square Park', '40');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('66', 'Harbourfront Centre', '82');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('67', 'Hart House Theatre', '111');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('68', 'High Park', '53');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('69', 'Historic Zion Schoolhouse', '24');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('70', 'Hockey Hall of Fame', '124');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('71', 'HTO Park', '41');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('72', 'Hudson''s Bay', '15');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('73', 'Humber Arboretum', '45');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('74', 'Humber Bay Park West (Humber Bay Butterfly Habitat)', '65');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('75', 'iArts Museum', '89');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('76', 'Illuminarium Toronto', '71');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('77', 'Isabel Bader Theatre', '9');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('78', 'Jack Layton Ferry Terminal', '88');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('79', 'James Garden Park', '129');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('80', 'Kew Gardens Park', '136');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('81', 'Koerner Hall (at the Telus Centre for Performance and Learning)', '63');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('82', 'Little Canada', '139');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('83', 'Mackenzie House', '81');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('84', 'Marie Curtis Park East Beach', '136');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('85', 'Massey Hall', '33');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('86', 'Mattamy Athletic Centre', '123');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('87', 'Medieval Times Dinner and Tournament', '5');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('88', 'Mel Lastman Square', '41');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('89', 'Meridian Arts Centre (formerly Toronto Centre for the Arts)', '28');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('90', 'Meridian Hall (formerly Sony Centre for the Performing Arts)', '135');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('91', 'Metro Toronto Convention Centre', '72');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('92', 'Montgomery''s Inn', '12');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('93', 'Museum of Contemporary Canadian Art', '33');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('94', 'Museum of Illusions Toronto', '48');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('95', 'Mysteriously Yours Mystery Dinner Theatre', '62');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('96', 'Native Earth Performing Arts & Aki Studio', '37');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('97', 'Old City Hall', '99');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('98', 'Onsite Gallery [at] OCADU', '104');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('99', 'Osgoode Hall', '35');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('100', 'Polson Pier', '101');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('101', 'Princess of Wales Theatre', '131');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('102', 'Queen Elizabeth Theatre', '1');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('103', 'Queen''s Park: Legislative Assembly of Ontario', '5');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('104', 'Randolph Centre for the Arts', '103');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('105', 'Redpath Sugar Museum', '27');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('106', 'Ripley''s Aquarium of Canada', '137');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('107', 'Riverdale Farm', '15');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('108', 'Riverdale Park (East and West)', '90');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('109', 'Rogers Centre', '42');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('110', 'Rosetta McClain Gardens', '124');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('111', 'Rouge Beach Park', '63');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('112', 'Rouge National Urban Park', '96');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('113', 'Rouge Valley Conservation Centre', '52');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('114', 'Roy Thomson Hall', '96');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('115', 'Royal Alexandra Theatre', '132');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('116', 'Royal Conservatory of Music', '29');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('117', 'Royal Ontario Museum', '36');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('118', 'Sankofa Square (formerly known as Yonge-Dundas Square)', '13');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('119', 'Sarah and Chaim Neuberger Holocaust Education Centre', '71');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('120', 'Centennial Scarborough Museum', '86');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('121', 'Centennial Scarborough Village Theatre', '28');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('122', 'Scotiabank Arena', '66');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('123', 'Soulpepper Theatre Company', '45');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('124', 'Spadina Museum', '62');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('125', 'St. James Park', '134');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('126', 'St. Lawrence Centre for the Arts', '28');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('127', 'St. Lawrence Market and Market Gallery', '28');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('128', 'Steam Whistle Brewery', '108');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('129', 'Sugar Beach Park', '44');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('130', 'Sunnyside Beach', '84');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('131', 'Taras H. Shevchenko Museum', '30');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('132', 'Tarragon Theatre', '75');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('133', 'Textile Museum of Canada', '128');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('134', 'The 48th Highlanders Museum', '92');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('135', 'The Danforth Music Hall', '129');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('136', 'The Distillery Historic District', '121');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('137', 'The Image Centre (formerly known as Ryerson Image Centre)', '27');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('138', 'The Japan Foundation', '121');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('139', 'The Power Plant Contemporary Art Gallery', '116');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('140', 'The Second City', '3');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('141', 'The Theatre Centre', '103');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('142', 'The Village Players', '137');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('143', 'The Well', '62');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('144', 'Theatre Passe Muraille', '51');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('145', 'Thompson Landry Gallery - Stone Building & Cooperage Space', '59');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('146', 'TIFF Bell Lightbox', '118');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('147', 'Todmorden Mills Heritage Site', '96');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('148', 'Tommy Thompson Park', '113');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('149', 'Toronto Botanical Gardens and Edwards Gardens', '62');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('150', 'Toronto City Hall and Nathan Phillips Square', '52');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('151', 'Toronto Congress Centre', '12');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('152', 'Toronto Island Park', '39');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('153', 'Toronto Metropolitan University Theatre (formerly known as Ryerson Theatre)', '130');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('154', 'Toronto Music Garden', '131');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('155', 'Toronto Pearson International Airport', '113');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('156', 'Toronto Police Museum & Discovery Centre', '101');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('157', 'Toronto Railway Museum', '113');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('158', 'Toronto Reference Library', '81');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('159', 'Toronto Sculpture Garden', '113');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('160', 'Toronto Tourist Information Centre', '2');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('161', 'Toronto Zoo', '130');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('162', 'Toronto''s First Post Office', '54');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('163', 'Travellers'' Aid Society of Toronto', '87');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('164', 'Trinity Square', '129');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('165', 'Ukrainian Museum of Canada', '126');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('166', 'Union Station', '130');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('167', 'Union Station Bus Terminal', '53');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('168', 'Village at Black Creek (Black Creek Pioneer Village)', '68');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('169', 'Village of Yorkville Park', '123');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('170', 'Ward''s Island Beach', '38');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('171', 'Winchester Street Theatre', '24');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('172', 'Woodbine Beach', '69');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('173', 'Woodbine Racetracks', '116');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('174', 'Woodbine Shopping Centre and Fantasy Fair', '98');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('175', 'Yorkdale Shopping Centre', '139');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('176', 'Young Centre for the Performing Arts', '97');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('177', 'Young People''s Theatre', '124');
INSERT INTO attractions (attraction_id, attraction_name, neighbourhood_id) VALUES ('178', 'Yuk Yuk''s', '70');
